# Generated by Django 2.2.4 on 2020-01-07 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
