# Generated by Django 2.2.4 on 2020-01-08 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookgenre',
            name='description',
        ),
        migrations.AddField(
            model_name='bookgenre',
            name='genre',
            field=models.SmallIntegerField(choices=[(0, 'Fantasy'), (1, 'Horror'), (2, 'Sci-fi'), (3, 'Romance')], default=None),
        ),
    ]
